blank_issues_enabled: true
contact_links:
  - name: Infinytum Discord
    url: https://discord.gg/PSfKAQWPa4
    about: If you have a question, or are looking for advice, please check out our Discord.
