name: Security
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  security:
    name: Security
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v3
      - name: Run Gosec
        uses: securego/gosec@master
        with:
          args: -exclude-dir=internal/*/ ./...
      - name: Run Govulncheck
        uses: kmulvey/govulncheck-action@v1.0.0